#!/usr/bin/env bash
set -euo pipefail

REPOSITORY="${MIHOMO_USER_KIT_REPOSITORY:-Zijian-Wu/mihomo-user-kit}"
REPOSITORY_REF="${MIHOMO_USER_KIT_REF:-main}"
RAW_BASE="${MIHOMO_USER_KIT_RAW_BASE:-https://raw.githubusercontent.com/$REPOSITORY/$REPOSITORY_REF}"
REPO_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" 2>/dev/null && pwd || pwd)"
LOCAL_BIN="$HOME/.local/bin"
CONFIG_ROOT="${MIHOMO_CONFIG_DIR:-$HOME/.config/mihomo}"
CENTRAL_MIHORO_CONFIG="$CONFIG_ROOT/mihoro.toml"
DEFAULT_MIHORO_CONFIG="$HOME/.config/mihoro.toml"
SHELL_CONFIG_DIR="$CONFIG_ROOT/shell"
MIHORO_RELEASE_API="${MIHORO_RELEASE_API:-https://api.github.com/repos/spencerwooo/mihoro/releases/latest}"

RUN_INIT=0
ENABLE_CODEX=0
CHECK_ONLY=0
TEMP_DIR=""

usage() {
  cat <<'USAGE'
Usage: bash install.sh [options]

Options:
  --check          Check dependencies and current installation only
  --init           Run `mihoro init`, normalize GeoData, and start Mihomo
  --enable-codex   Install the optional Codex proxy shell function
  -h, --help       Show this help

Environment:
  MIHOMO_USER_KIT_REPOSITORY  Source repository for helper scripts
  MIHOMO_USER_KIT_REF         Source branch or tag (default: main)
  MIHOMO_USER_KIT_RAW_BASE    Override the raw download base URL
  MIHOMO_CONFIG_DIR           Override the centralized config directory
  MIHORO_TARGET               Override the Mihoro release target triple
  MIHORO_RELEASE_API          Override the Mihoro latest-release API URL
  MIHORO_GITHUB_MIRROR        Prefix GitHub artifact downloads with a mirror

By default, the latest x86_64 or aarch64 Linux musl build of Mihoro is used.
The installer prepares Mihoro with `mihoro_user_agent = "mihomo"` before the
first subscription download. It never runs sudo, a system package manager,
systemctl, or configures boot-time startup.
USAGE
}

cleanup() {
  if [[ -n "$TEMP_DIR" ]]; then
    rm -rf -- "$TEMP_DIR"
  fi
}
trap cleanup EXIT

while (( $# > 0 )); do
  case "$1" in
    --check) CHECK_ONLY=1 ;;
    --init) RUN_INIT=1 ;;
    --enable-codex) ENABLE_CODEX=1 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage >&2; exit 2 ;;
  esac
  shift
done

required_commands=(bash sh curl tar tmux mktemp install ln mv readlink grep awk touch uname mkdir rm dirname cut head)
optional_commands=(git bwrap zsh)
missing_required=()
missing_optional=()

for command_name in "${required_commands[@]}"; do
  command -v "$command_name" >/dev/null 2>&1 || missing_required+=("$command_name")
done

for command_name in "${optional_commands[@]}"; do
  command -v "$command_name" >/dev/null 2>&1 || missing_optional+=("$command_name")
done

detect_mihoro_target() {
  if [[ -n "${MIHORO_TARGET:-}" ]]; then
    printf '%s\n' "$MIHORO_TARGET"
    return 0
  fi

  case "$(uname -m)" in
    x86_64|amd64) printf '%s\n' 'x86_64-unknown-linux-musl' ;;
    aarch64|arm64) printf '%s\n' 'aarch64-unknown-linux-musl' ;;
    *)
      echo "Unsupported architecture: $(uname -m)" >&2
      echo 'Set MIHORO_TARGET to a release target provided by Mihoro.' >&2
      return 1
      ;;
  esac
}

MIHORO_RESOLVED_TARGET="$(detect_mihoro_target)"
printf 'HOME: %s\n' "$HOME"
printf 'Architecture: %s\n' "$(uname -m)"
printf 'Mihoro target: %s\n' "$MIHORO_RESOLVED_TARGET"
printf 'Config directory: %s\n' "$CONFIG_ROOT"

if (( ${#missing_required[@]} > 0 )); then
  printf 'Missing required commands: %s\n' "${missing_required[*]}" >&2
  cat >&2 <<'NOTICE'
Ask the server administrator to install the missing packages. This installer
will not request sudo access. Common Debian/Ubuntu packages include:
ca-certificates, curl, tar, tmux, gawk, and coreutils.
NOTICE
  exit 1
fi

if (( ${#missing_optional[@]} > 0 )); then
  printf 'Missing optional commands: %s\n' "${missing_optional[*]}"
  echo 'git is only needed for cloning; bwrap may be used by Codex; zsh is optional.'
fi

if command -v mihoro >/dev/null 2>&1 || [[ -x "$LOCAL_BIN/mihoro" ]]; then
  echo 'Mihoro: installed'
else
  echo 'Mihoro: not installed'
fi

if [[ -x "$LOCAL_BIN/mihomo" ]]; then
  echo 'Mihomo core: installed'
else
  echo 'Mihomo core: not installed (downloaded by `mihoro init`)'
fi

if [[ -f "$CONFIG_ROOT/config.yaml" ]]; then
  echo 'Mihomo config: present'
else
  echo 'Mihomo config: missing (generated by `mihoro init`)'
fi

if [[ -f "$DEFAULT_MIHORO_CONFIG" ]]; then
  current_user_agent="$(awk -F '"' '/^[[:space:]]*mihoro_user_agent[[:space:]]*=/ { print $2; exit }' "$DEFAULT_MIHORO_CONFIG")"
  printf 'Mihoro user agent: %s\n' "${current_user_agent:-not set}"
else
  echo 'Mihoro user agent: config not created yet'
fi

if (( CHECK_ONLY )); then
  exit 0
fi

mkdir -p "$LOCAL_BIN" "$CONFIG_ROOT" "$SHELL_CONFIG_DIR"

ensure_line() {
  local file="$1"
  local line="$2"
  touch "$file"
  grep -qxF "$line" "$file" 2>/dev/null || printf '\n%s\n' "$line" >> "$file"
}

ASSET_RESULT=""
asset_path() {
  local relative_path="$1"
  local local_path="$REPO_DIR/$relative_path"

  if [[ -f "$local_path" ]]; then
    ASSET_RESULT="$local_path"
    return 0
  fi

  if [[ -z "$TEMP_DIR" ]]; then
    TEMP_DIR="$(mktemp -d)"
  fi

  local downloaded_path="$TEMP_DIR/$(basename -- "$relative_path")"
  if [[ ! -f "$downloaded_path" ]]; then
    echo "Downloading $relative_path from $REPOSITORY@$REPOSITORY_REF ..." >&2
    curl -fsSL "$RAW_BASE/$relative_path" -o "$downloaded_path"
  fi
  ASSET_RESULT="$downloaded_path"
}

install_mihoro() {
  if [[ -z "$TEMP_DIR" ]]; then
    TEMP_DIR="$(mktemp -d)"
  fi

  local release_json package_url download_url archive extract_dir
  release_json="$(curl -fsSL "$MIHORO_RELEASE_API")"
  package_url="$(
    printf '%s\n' "$release_json" \
      | grep '"browser_download_url"' \
      | cut -d '"' -f 4 \
      | grep -- "-${MIHORO_RESOLVED_TARGET}\\.tar\\.gz$" \
      | head -n 1 \
      || true
  )"

  if [[ -z "$package_url" ]]; then
    echo "No Mihoro release asset found for: $MIHORO_RESOLVED_TARGET" >&2
    return 1
  fi

  download_url="$package_url"
  if [[ -n "${MIHORO_GITHUB_MIRROR:-}" ]]; then
    download_url="${MIHORO_GITHUB_MIRROR%/}/$package_url"
  fi

  archive="$TEMP_DIR/mihoro.tar.gz"
  extract_dir="$TEMP_DIR/mihoro-extract"
  mkdir -p "$extract_dir"

  echo "Downloading Mihoro ($MIHORO_RESOLVED_TARGET) ..."
  curl -fL "$download_url" -o "$archive"
  tar -xzf "$archive" -C "$extract_dir"

  if [[ ! -f "$extract_dir/mihoro" ]]; then
    echo 'The Mihoro archive did not contain the expected `mihoro` binary.' >&2
    return 1
  fi

  install -m 0755 "$extract_dir/mihoro" "$LOCAL_BIN/mihoro"
  echo "Installed Mihoro to: $LOCAL_BIN/mihoro"
}

# Keep the actual Mihoro config inside the centralized Mihomo directory while
# preserving Mihoro's default lookup path through a symlink.
if [[ -e "$DEFAULT_MIHORO_CONFIG" && ! -L "$DEFAULT_MIHORO_CONFIG" ]]; then
  if [[ ! -e "$CENTRAL_MIHORO_CONFIG" ]]; then
    mv -- "$DEFAULT_MIHORO_CONFIG" "$CENTRAL_MIHORO_CONFIG"
    ln -s -- "$CENTRAL_MIHORO_CONFIG" "$DEFAULT_MIHORO_CONFIG"
    echo "Moved Mihoro config to: $CENTRAL_MIHORO_CONFIG"
  else
    echo 'Two Mihoro config files exist; neither was overwritten:' >&2
    echo "  $DEFAULT_MIHORO_CONFIG" >&2
    echo "  $CENTRAL_MIHORO_CONFIG" >&2
    echo 'Merge them manually, then replace the first path with a symlink.' >&2
  fi
elif [[ ! -e "$DEFAULT_MIHORO_CONFIG" && ! -L "$DEFAULT_MIHORO_CONFIG" ]]; then
  ln -s -- "$CENTRAL_MIHORO_CONFIG" "$DEFAULT_MIHORO_CONFIG"
elif [[ -L "$DEFAULT_MIHORO_CONFIG" ]]; then
  current_target="$(readlink "$DEFAULT_MIHORO_CONFIG")"
  if [[ "$current_target" != "$CENTRAL_MIHORO_CONFIG" && "$current_target" != "mihomo/mihoro.toml" ]]; then
    echo "Existing Mihoro config symlink points elsewhere; keeping it: $current_target" >&2
  fi
fi

PATH_LINE='export PATH="$HOME/.local/bin:$PATH"'
ensure_line "$HOME/.profile" "$PATH_LINE"
[[ -f "$HOME/.bashrc" || "${SHELL:-}" == */bash ]] && ensure_line "$HOME/.bashrc" "$PATH_LINE"
[[ -f "$HOME/.zshrc" || "${SHELL:-}" == */zsh ]] && ensure_line "$HOME/.zshrc" "$PATH_LINE"
export PATH="$LOCAL_BIN:$PATH"

for script in mihomo-tmux with-mihomo mihomo-normalize-geodata mihomo-update-geodata mihomo-set-user-agent; do
  asset_path "scripts/$script"
  install -m 0755 "$ASSET_RESULT" "$LOCAL_BIN/$script"
done

echo "Installed user commands to: $LOCAL_BIN"

if ! command -v mihoro >/dev/null 2>&1 && [[ ! -x "$LOCAL_BIN/mihoro" ]]; then
  install_mihoro
else
  echo 'Skipping Mihoro installation: already installed.'
fi

if [[ -x "$LOCAL_BIN/mihoro" ]]; then
  MIHORO_BIN="$LOCAL_BIN/mihoro"
else
  MIHORO_BIN="$(command -v mihoro || true)"
fi

if [[ -z "$MIHORO_BIN" || ! -x "$MIHORO_BIN" ]]; then
  echo 'Mihoro executable could not be resolved after installation.' >&2
  exit 1
fi

# Trigger Mihoro's own default-config writer without downloading anything.
# It exits non-zero because the subscription URL is empty; that is expected.
if [[ ! -f "$DEFAULT_MIHORO_CONFIG" ]]; then
  "$MIHORO_BIN" status >/dev/null 2>&1 || true
fi

if [[ ! -f "$DEFAULT_MIHORO_CONFIG" ]]; then
  echo "Mihoro did not create its default config: $DEFAULT_MIHORO_CONFIG" >&2
  exit 1
fi

"$LOCAL_BIN/mihomo-set-user-agent" --config "$DEFAULT_MIHORO_CONFIG" --quiet
echo 'Configured Mihoro subscription User-Agent: mihomo'

if (( ENABLE_CODEX )); then
  asset_path scripts/codex-proxy.sh
  install -m 0644 "$ASSET_RESULT" "$SHELL_CONFIG_DIR/codex-proxy.sh"
  CODEX_LINE="source \"$SHELL_CONFIG_DIR/codex-proxy.sh\""
  [[ -f "$HOME/.bashrc" || "${SHELL:-}" == */bash ]] && ensure_line "$HOME/.bashrc" "$CODEX_LINE"
  [[ -f "$HOME/.zshrc" || "${SHELL:-}" == */zsh ]] && ensure_line "$HOME/.zshrc" "$CODEX_LINE"
  echo 'Enabled the optional Codex proxy wrapper.'
fi

if (( RUN_INIT )); then
  set +e
  "$MIHORO_BIN" init
  init_status=$?
  set -e

  if [[ -x "$LOCAL_BIN/mihomo" && -f "$CONFIG_ROOT/config.yaml" ]]; then
    if (( init_status != 0 )); then
      echo '`mihoro init` returned an error, but the core and config exist.'
      echo 'This commonly means the final systemd step is unavailable.'
    fi
    "$LOCAL_BIN/mihomo-normalize-geodata"
    "$LOCAL_BIN/mihomo-tmux" start
  else
    echo '`mihoro init` did not produce both the core and config.' >&2
    exit "${init_status:-1}"
  fi
fi

cat <<'DONE'

Installation complete.

Next steps:
  mihoro init
  mihomo-tmux start

Useful commands:
  mihomo-tmux --help
  with-mihomo --help
  mihomo-set-user-agent --help
  mihomo-update-geodata --help

Configuration is stored under ~/.config/mihomo/.
The subscription User-Agent is set to "mihomo" before initialization.
No systemd service or boot-time startup is configured.
DONE
